export const categoryOrder: Record<string, number> = {
  ".NET": 1,
  "Design & Architecture": 2,
  SQL: 3,
  React: 4,
  Azure: 5,
};

export const topicOrder: Record<string, Record<string, number>> = {
  ".NET": {
    "C# Language Foundations": 1,
    "Modern C# patterns": 2,
    "Async programming, tasks, cancellation, and concurrency": 3,
    "Dependency injection, configuration, middleware, and logging": 4,
    "API design and implementation": 5,
    "Authentication, authorization, and web security": 6,
    "Entity Framework": 7,
    "Testing strategy and integration testing": 8,
    "Performance, scalability, and caching": 9,
  },
  "Design & Architecture": {
    "Requirements decomposition and system trade-offs": 1,
    "Software design principles and common .NET patterns": 2,
    "Clean Architecture and modular boundaries": 3,
    "Domain modeling and Domain-Driven Design": 4,
    "API design and integration contracts": 5,
    "Web application security threat modeling and attack patterns": 6,
    "Distributed systems patterns": 7,
    "Scalability, resilience, caching, and observability design": 8,
    "Testing strategy, maintainability, and technical leadership": 9,
  },
  SQL: {
    "Relational modeling and normalization": 1,
    "Core querying and data retrieval": 2,
    "SQL practical interview comparisons and SQL Server-specific features": 3,
    "Advanced querying with window functions and CTEs": 4,
    "Indexes, statistics, and execution plans": 5,
    "Transactions, isolation, locking, and deadlocks": 6,
    "Query tuning, Query Store, and plan stability": 7,
    "Database programmability and schema evolution": 8,
    "Backup, recovery, HA/DR, security, and temporal data": 9,
  },
  React: {
    "JavaScript fundamentals": 1,
    "TypeScript for React": 2,
    "Components, props, state, and rendering behavior": 3,
    "Hooks, effects, and custom hooks": 4,
    "Routing, forms, and server communication": 5,
    "Production data access, API clients, and frontend auth": 6,
    "Forms, validation, and frontend performance in production": 7,
    "State management, performance, and rendering optimization": 8,
    "Testing, accessibility, and frontend debugging": 9,
  },
  Azure: {
    "Azure compute choices and hosting models": 1,
    "Azure Functions and Durable Functions": 2,
    "Identity, secrets, and access control": 3,
    "Networking, API edge, and secure connectivity": 4,
    "Azure data, storage, and caching services": 5,
    "Azure Blob Storage and file handling": 6,
    "Messaging and event-driven Azure integration": 7,
    "Monitoring, tracing, and incident response on Azure": 8,
    "Delivery, infrastructure as code, scaling, and cost control": 9,
  },
};
